// src/constants/typeColors.ts
export const typesByColor = [
  { name: "normal", bg: "bg-gray-400" },
  { name: "flying", bg: "bg-sky-300" },
  { name: "fighting", bg: "bg-orange-700" },
  { name: "rock", bg: "bg-amber-800" },
  { name: "ghost", bg: "bg-indigo-700" },
  { name: "ice", bg: "bg-cyan-300" },
  { name: "dragon", bg: "bg-indigo-900" },
  { name: "dark", bg: "bg-gray-800" },
  { name: "steel", bg: "bg-zinc-400" },
  { name: "grass", bg: "bg-green-500" },
  { name: "poison", bg: "bg-purple-500" },
  { name: "fire", bg: "bg-red-500" },
  { name: "water", bg: "bg-blue-500" },
  { name: "bug", bg: "bg-lime-500" },
  { name: "electric", bg: "bg-yellow-400" },
  { name: "ground", bg: "bg-yellow-700" },
  { name: "fairy", bg: "bg-pink-300" },
  { name: "psychic", bg: "bg-pink-600" },
];
